<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Web Challenge '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo 'home' ?>">Home</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Martin Ramos.</p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
<?php
echo $this->headLink()
    ->prependStylesheet($this->basePath('DataTables/DataTables-1.10.12/css/dataTables.bootstrap.min.css'))
    ->prependStylesheet($this->basePath('DataTables/datatables.min.css'));

echo $this->headScript()
    ->prependFile($this->basePath('DataTables/datatables.min.js'))
    ->prependFile($this->basePath('DataTables/DataTables-1.10.12/js/dataTables.bootstrap.min.js'))
    ->prependFile($this->basePath('DataTables/DataTables-1.10.12/js/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('js/tasks/dataTableTask.js'))
    ->prependFile($this->basePath('js/tasks/tasks.js'))
    ->prependFile($this->basePath('js/taskInit.js'));
?>
</html>
