<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <!-- Profile section -->
            <div class="span3 well" id="profile">
                <section>
                    <a href="<?php echo $this->url('wall', array('username' => 'martin')) ?>" title="<?php printf('%s %s', 'martin', 'martin')  ?>" class="thumbnail">
                        <img src="/images/avatar.png" alt="<?php printf('%s %s', 'martin', 'martin')  ?>" />
                    </a>
                    <ul>
                        <li>
                            <h3><i class="icon-user"></i> <?php echo $this->translate('Bio') ?></h3>
                            <p><?php echo 'martin' ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-globe"></i> <?php echo $this->translate('Location') ?></h3>
                            <p><?php echo 'martin' ?></p>
                        </li>
                        <li>
                            <h3><i class="icon-heart"></i> <?php echo $this->translate('Gender') ?></h3>
                            <p><?php echo 'martin' ?></p>
                        </li>
                    </ul>
                </section>
            </div>

            <!-- Wall profile -->
            <div class="span9" id="wall">
                <section>
                    <!-- Main Stream wall profile -->
                    <div id="wall-stream">
                        <h2><?php printf('%s %s', 'martin', 'martin')  ?></h2>
                    </div>
                    <section>
            </div> <!-- Close wall profile -->
        </div>
    </div>
</div>