<?php
    $this->headScript()->captureStart()
?>
    var taskRows = <?php echo $task; ?>;
<?php
    $this->headScript()->captureEnd()
?>
<article>
    <h1>TODO LIST</h1>
    <form id="taskForm" class="form-horizontal">
        <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input type="name" class="form-control" id="name" placeholder="Task Name" name="name" value="">
            </div>
        </div>
        <div class="form-group">
            <label for="status" class="col-sm-2 control-label">Status</label>
            <div class="col-sm-10">
                <select class="form-control" name="status">
                    <option value="1">Complete</option>
                    <option value="2">Incomplete</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="send-task" type="submit" class="btn btn-default">Add task</button>
            </div>
        </div>
        <input type="hidden" value="" name="id">
    </form>

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Create a todo list!</td>
                <td>Incomplete</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Work</td>
                <td>Incomplete</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Be an architect</td>
                <td>Incomplete</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
        </tbody>
    </table>

</article>